### ISSUE TITLE
Device Not Compatible

### ISSUE THREAD

**Issue by SteadyStatus21** [zacharee/SystemUITunerSystemSettings#3]
Android 14 BETA QPR 1. 
Upon installing, I am told that the app is not compatible with my version of Android. 

![Screenshot_20231107-072630](https://github.com/zacharee/SystemUITunerSystemSettings/assets/73841304/372ac23a-ad16-48ec-b761-eb1dea0e04ba)

**Comment by SteadyStatus21** [comment]
![Screenshot_20231107-072755](https://github.com/zacharee/SystemUITunerSystemSettings/assets/73841304/44f8556a-672f-4cfc-8b35-ab3f745846c7)

**Comment by alavijay** [comment]
+1 for the issue

**Comment by Castald0** [comment]
+1 as well

**Comment by sansnil** [comment]
+1 Seeing this as well.
Is there a newer version?

**Comment by zacharee** [comment]
This is worked around in version 1.2. Unfortunately, it means you need to use a special process to install, which is outlined in the new README.

**Comment by SteadyStatus21** [comment]
> This is worked around in version 1.2. Unfortunately, it means you need to use a special process to install, which is outlined in the new README.

Thank you @zacharee!
