### ISSUE TITLE
Invalid package, won't update 

### ISSUE THREAD

**Issue by jairjacom** [zacharee/SystemUITunerSystemSettings#4]
Hi, since released version 359 for main app, this newer add on version 1.2 will not install/update. Running Android 14 on a Samsung S21+.
App asks to update addon or open shizuku. Any suggestions on how I can provide more feedback for this problem?

**Comment by bilemke** [comment]
@zacharee  Looks like you left:

android:testOnly="true"

in AndroidManifest.xml so it is seeing it as a test package.

@jairjacom You can get it to install with the test package flag still if you add on to the usual "adb install --bypass-low-target-sdk-block" command currently needed to install on Android 14 bypassing the low SDK version by adding in "-t" as a argument to "adb install".. So, the command would be like this:

adb install -t --bypass-low-target-sdk-block app-release.apk

**Comment by zacharee** [comment]
The test flag is intentional. See the readme.

**Comment by jairjacom** [comment]
Thanks, I'm not to savvy for what you explained. I was hoping a regular installation. I will try to do what you say.

**Comment by jairjacom** [comment]
I tried with the install with option app and it went thru install fine. The part I'm stuck is with the additional adb command. So I can't use the app yet.

**Comment by zacharee** [comment]
You only need Install with Options or ADB, not both.

Zachary Wander

Website | GitHub | Mastodon | LinkedIn

**Comment by jairjacom** [comment]
![Screenshot_20240204_183430_SystemUI Tuner](https://github.com/zacharee/SystemUITunerSystemSettings/assets/80634190/7aa33bcf-d5ff-4ca3-977a-74ffa4fe2230)
![Screenshot_20240204_183313_Install with Options](https://github.com/zacharee/SystemUITunerSystemSettings/assets/80634190/b13d5567-12d0-4f9b-944e-92759dd68234)

**Comment by jairjacom** [comment]
I may be doing something wrong 🤷‍♂️

**Comment by zacharee** [comment]
Enable the "Replace Existing" as well. I've updated the instructions to include that.

**Comment by jairjacom** [comment]
Ok, that worked. Although when I try to make a change the app keeps giving me the blue screen above.

**Comment by zacharee** [comment]
SystemUI Tuner 360 and Add-On 1.3 should be more stable.

https://github.com/zacharee/Tweaker/releases/tag/360

**Comment by CamsShaft** [comment]
Apologies for beating a dead horse here, but I'm getting this:
"tk.zwander.systemuituner.systemsettings: INSTALL_FAILED_DUPLICATE_PERMISSION: Package tk.zwander.systemuituner.systemsettings attempting to redeclare permission com.zacharee1.systemuituner.permission.WRITE_SETTINGS already owned by com.zacharee1.systemuituner"
         Which is fine I guess if it's already set... shizuku is good as always too. I'm still getting the blue screen as pictured a few posts above. I'm going to take a wild guess here and predict it's because I'm using a Samsung S22 upgraded to the latest enforcement policies and revocations possible. I haven't tried adb install yet only because I feel it would be a waste of time just to get an error. Not sure where to go from here since system shell won't work and dirty pipe is out of the question now too. Toss this phone in the garbage soon? 🤣
